### ISSUE TITLE
Unable to add plugin

### ISSUE THREAD

**Issue by clashcaddie** [Irineu333/Highlight#19]
When i add implementation "com.github.Irineu333:Highlight:1.0.4"

It tells me it cannot find that version to download

**Comment by Irineu333** [comment]
Did you add jitpack to the project?

**Comment by Irineu333** [comment]
Please, use "implementation "com.github.Irineu333:Highlight:v1.0.4"

**Comment by Irineu333** [comment]
I tested it here and it's working.

![image](https://github.com/Irineu333/Highlight/assets/45833588/bece527f-05af-4865-83c9-6730575f76cb)

If it still doesn't work, use the AAR file available in the release.

**Comment by Irineu333** [comment]
The library is now available on Maven Central (previously it was on JitPack), which should eliminate any availability issues.
