### ISSUE TITLE
Unable to use the library

### ISSUE THREAD

**Issue by MoanneCompany** [Irineu333/Highlight#21]
I added `implementation "com.github.Irineu333:Highlight:1.0.4"` but when i'll use this in my source code it not such a directory (i added the jitpack url)

**Comment by Irineu333** [comment]
Did you get it resolved? (given my delay in replying, sorry)

**Comment by Irineu333** [comment]
Please, use `implementation "com.github.Irineu333:Highlight:v1.0.4"`

**Comment by Irineu333** [comment]
I tested it here and it's working.
![image](https://github.com/Irineu333/Highlight/assets/45833588/bece527f-05af-4865-83c9-6730575f76cb)

If it still doesn't work, use the AAR file available in the release.

**Comment by Irineu333** [comment]
Now that the library has been added to Maven Central, these problems will no longer occur.
